// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:1cdbaa4b-f798-43c5-ae76-d2a01e5e3844",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_2tBQ0rieC",
    "aws_user_pools_web_client_id": "2mqa2q6k0nhf18merovhjhvs7u"
};


export default awsmobile;
